### ISSUE TITLE
Implement Templating System

### ISSUE THREAD

**Issue by jmwright** [7BIndustries/sliderule-cli#12]
With needing to put custom info (component name and license) in files like package.json, the current hard-coded templates are not sustainable. Separating the templates out into separate files would allow other users to contribute to them more easily as well.

[Liquid](http://cobalt-org.github.io/liquid-rust/liquid/index.html) is a decently powerful  templating engine that doesn't bring a lot of cruft and tedious complexity with it, which seems to be a problem with most other templating crates.

The cargo command does not allow you to copy files and directories to target directories after a build. I'll need to create a [wrapper script](https://stackoverflow.com/questions/31080757/copy-files-to-the-target-directory-after-build) for building the CLI to copy the `templates` directory to either `target/debug` or `target/release`, whichever is appropriate.

**Comment by jmwright** [comment]
@m30-jrs Maybe Liquid (or one of its alternatives) is also something to keep in mind as we get closer to creating a documentation framework/methodology/process that is built like code rather than being maintained by hand. If sliderule-cli is already doing templating for project management templates, maybe the docs can piggy-back on that functionality.

**Comment by m30-jrs** [comment]
Yeah, a templating engine would address many of the needs for generating documentation from content + data.  That is, after all, what they are for.  I think the other real trick will be finding a good way to create PDFs from the source materials.  

A little quick searching turned up this rather interesting option: [weasy](https://weasyprint.org/start/).  But, it is Python, so we end up down the rabbit hole of how do you distribute Python tools to end users in a packaged way.....
