### ISSUE TITLE
Suggested README template changes

### ISSUE THREAD

**Issue by m30-jrs** [7BIndustries/sliderule-cli#14]
As part of an effort to more concretely brand Sliderule and DOF, I suggest the following format for the README template used to create README files in new component directories.

```
# <new component name>
<new component name> component description.

---
Developed in [Sliderule](http://sliderule.io) an implementation of the [Distributed OSHW Framework](http://dof.sliderule.io).
```

And yes, dof.sliderule.io works.

**Comment by m30-jrs** [comment]
Sounds like a plan to me.

**Comment by jmwright** [comment]
This change has been made.

@m30-jrs Feel free to reopen if something looks amiss with the [readme template](https://github.com/7BIndustries/sliderule-cli/blob/master/templates/README.md.liquid).
