### ISSUE TITLE
Add yes Answer Argument for remove Command

### ISSUE THREAD

**Issue by jmwright** [7BIndustries/sliderule-cli#20]
Currently I have the code to confirm that a user wants to remove a component commented out. This is because the test suite won't run to completion for that command because it will wait for user input. Something like a `-y` option needs to be added to automatically answer yes. This is similar to how the apt command works in Ubuntu. There's a `-y` option to allow for unattended updates.

**Comment by m30-jrs** [comment]
+1

**Comment by jmwright** [comment]
Implemented in commit f429c407fcc91c2232dea144c9ff06f47359d22f
