### ISSUE TITLE
Add version command

### ISSUE THREAD

**Issue by jedibfa** [7BIndustries/sliderule-cli#38]
Now that we are posting actual versioned releases, we need a way to tell what version of SR we are running.  Recommend a --version/-V cli option that reports the version info (release number, build date/info, etc).

**Comment by jmwright** [comment]
@jedibfa It's still an overly simplistic implementation, but this has been added in master as of commit a636b1dbc9f2c029e1ec1e72daf3d05eda28d9c0

I would still like to automate the version number and build info, but that will have to wait. All the ways I could do that right now add extra build system complexity, some of which I just got away from not long ago.
